### ISSUE TITLE
Exclude some DSIDs from aggregate downloads count

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_usage_stats_charts#11]
Related to https://github.com/mjordan/islandora_usage_stats_csv/issues/3.

**Comment by mjordan** [comment]
@bondjimbond when you get a minute I'd appreciate it if you could test the issue-11 branch here as well. Both this and the CSV module have a similar option to exclude datastreams from their output, with a note in each module's admin form to make sure the list of DSIDs for both modules is the same.

**Comment by bondjimbond** [comment]
@mjordan I'll give this a test. But a thought... If Charts is a dependency for CSV, why not have a single exclusion list that they both draw from?

**Comment by mjordan** [comment]
Neither is a dependency of the other.

**Comment by bondjimbond** [comment]
Ah! I thought CSV was attached somehow. Never mind then.

Although it may be useful to group these as a pair of submodules to a more general parent module that groups their related functions - "islandora usage stats displays" or something like that.

**Comment by mjordan** [comment]
No, at the risk of duplicate code, I wanted to keep them separate since someone may want to provide CSV reports without using Charts. And vice versa. Also, I have bigger plans for the CSV module.... monthly reports emailed to researchers just like the commercial repo services do.

**Comment by bondjimbond** [comment]
Ooh, I'm looking forward to that one! That's something I'd been thinking about for a couple of years.

**Comment by mjordan** [comment]
We have to make some decisions internally as part of our Summit migration to Scholar but it'll happen.

**Comment by bondjimbond** [comment]
Tested the branch. Works as advertised! And nice to see the Views outnumbering the Downloads finally.

**Comment by mjordan** [comment]
@bondjimbond thanks for testing. Resolved with be959038421f8adebcc63105d4e8558155d8b710.
