### ISSUE TITLE
Query: The Statistics link expand/collapse code

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_usage_stats_charts#16]
I'd like to steal the code that allows the Statistics block to expand and collapse. Can you point me to where exactly it lives and which files it requires so I can hack it into my own module?

**Comment by mjordan** [comment]
It is a combination of 1) the right markup around what you want in the collapsable div and 2) including the right Javascript files when you render the div.

The markup is
```html
<fieldset class="islandora collapsible <?php print $collapsed; ?>">
<div>
...
 </div>
</fieldset>
```

 (see https://github.com/mjordan/islandora_usage_stats_charts/blob/7.x/theme/islandora_usage_stats_charts.tpl.php#L13). `$collapsed` should have the value "collapsed" or be an empty string to produce an open div.

You will need to include two Javascript files in the function where you render the markup. Do this with the following code:

```php
drupal_add_js('misc/collapse.js');
drupal_add_js('misc/form.js'); 
```

See https://github.com/mjordan/islandora_usage_stats_charts/blob/7.x/includes/blocks.inc#L47 for an example.

Happy hacking!

**Comment by bondjimbond** [comment]
Thanks, @mjordan! I'm trying what you said, and I think it's getting somewhere, but it's not quite there. Would you mind critiquing the code for me? This is a tool to generate embed code for Video objects.

I get the title and the div, but there's no collapsing behaviour and no link that might trigger the collapsed/expanded state. There are no anchor tags, so that seems like an obvious place to start, but I don't see them in your code either.

```
function islandora_video_embed_block_view($delta) {
  $to_render = array();

  drupal_add_js('misc/collapse.js');
  drupal_add_js('misc/form.js');

  $object = menu_get_object('islandora_object', 2);
// Exclude the Collection CModel from displaying the block
  if (!in_array("islandora:sp_videoCModel", $object->models)) {
    return;
  }
  global $base_url;
  $pid = $object->id;

  $dsid = "MP4";
  $width = "320";
  $height = "240";
  $collapsed = 'collapsed';

  $video_url = $base_url . '/islandora/object/' . $pid . '/datastream/' . $dsid . '/download/file.mp4';
  $embed_code =  '&lt;video width="' . $width . '" height="' . $height . '" controls&gt;
     &lt;source src="' . $video_url .'" type="video/mp4"&gt;
  &lt;/video&gt;';

  $embed_code = '<legend><span class="fieldset-legend">Video embed code</span></legend>' .
  '<fieldset class="islandora collapsible ' . $collapsed . '"><div>' .
    $embed_code . '</div></fieldset>';

  $to_render['content'] = $embed_code;

  return $to_render;
}
```

**Comment by mjordan** [comment]
You need the legend:

```html
<fieldset class="islandora collapsible <?php print $collapsed; ?>">
  <legend><span class="fieldset-legend"><?php print t('Usage statistics'); ?></span></legend>
```

Take a look at https://github.com/mjordan/islandora_usage_stats_charts/blob/7.x/theme/islandora_usage_stats_charts.tpl.php#L13. Sorry I didn't include that in my example.

**Comment by mjordan** [comment]
Oh, sorry, I see you've got the legend. Can you paste in some of the rendered HTML for me to look at? Not the PHP code, the HTML that is sent to the browser.

**Comment by bondjimbond** [comment]
```
<div id="block-islandora-video-embed-video-embed-object" class="block block-islandora-video-embed contextual-links-region">
   <div class="contextual-links-wrapper"><ul class="contextual-links"><li class="block-configure first last"><a href="/admin/structure/block/manage/islandora_video_embed/video_embed_object/configure?destination=islandora/object/islandora%3A103">Configure block</a></li>
 </ul></div>
  <div class="content">
  <legend><span class="fieldset-legend">Video embed code</span></legend><fieldset class="islandora collapsible collapsed"><div>&lt;video width="320" height="240" controls&gt;
  &lt;source src="http://localhost:8000/islandora/object/islandora:103/datastream/MP4/download/file.mp4" type="video/mp4"&gt;
  &lt;/video&gt;</div></fieldset>  </div>
  </div>
  </div>
  </div>

```

**Comment by mjordan** [comment]
The `<legend>` needs to be a child of the collapsible `<fieldset>`. Your HTML has it the other way around:

```html
<legend><span class="fieldset-legend">Video embed code</span></legend><fieldset class="islandora collapsible collapsed">
```

Can you try that?

**Comment by bondjimbond** [comment]
OK, that helped a little bit! Still messed up though..

```
<div class="content">
  <fieldset class="islandora collapsible collapsed"><legend><span class="fieldset-legend">Video embed code</span></legend><div>&lt;video width="320" height="240" controls&gt;
  &lt;source src="http://localhost:8000/islandora/object/islandora:103/datastream/MP4/download/file.mp4" type="video/mp4"&gt;
  &lt;/video&gt;</div></fieldset>  </div>
```
![screen shot 2018-05-09 at 10 27 53 am](https://user-images.githubusercontent.com/6069170/39820430-cb439c76-5373-11e8-97de-6a437d262b2a.png)

**Comment by mjordan** [comment]
There are encoded HTML entities in there that are breaking the rendering - if you remove them does it work?

**Comment by bondjimbond** [comment]
I commented out the content and changed $embed_code to simply "Test". Same result: you can click the link, a white box appears, can't click it away again. The content ("Test") is not visible because it's hidden behind the legend.


```
<div class="content">
  <fieldset class="islandora collapsible collapsed"><legend><span class="fieldset-legend">Video embed code</span></legend><div>Test</div></fieldset>  </div>
```

**Comment by bondjimbond** [comment]
I also tried moving the `<div>` from after `</legend>` to before `<legend>`. Same problem, and the legend is no longer clickable.

**Comment by mjordan** [comment]
Here's the markup from a usage stats block:

```html
<fieldset class="islandora collapsible collapsed">
  <legend><span class="fieldset-legend">Usage statistics</span></legend>
  <div class="fieldset-wrapper"><div id="islandora-usage-stats-charts-content"><canvas id="islandora-usage-stats-chart" height="400px" width="400px"></canvas></div>
    </div>
</fieldset>
```

The markup `<div id="islandora-usage-stats-charts-content"><canvas id="islandora-usage-stats-chart" height="400px" width="400px"></canvas></div>` is the content, the rest is the markup that makes the collapse stuff happen:

```html
<fieldset class="islandora collapsible collapsed">
  <legend><span class="fieldset-legend">Usage statistics</span></legend>
  <div class="fieldset-wrapper">

  <!-- your content goes here -->

    </div>
</fieldset>
```

Can you double check to confirm your markup follows that example?

**Comment by bondjimbond** [comment]
Ah, there's the problem! I needed `class="fieldset-wrapper"` for it to work. Thanks so much for your help!

I'll post a link to the module in a bit and then close the issue.

**Comment by mjordan** [comment]
:smiley:

**Comment by bondjimbond** [comment]
Module complete: https://github.com/bondjimbond/islandora_video_embed

**Comment by mjordan** [comment]
Nice!
