### ISSUE TITLE
Suggestion: Option to limit block visibility by CModel

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_usage_stats_charts#17]
Standard Drupal block options can limit block visibility by path, but CModels aren't in the path. Should be easy enough to configure implementation according to selected CModels -- see Islandora Badges for [copypasta code](https://github.com/Islandora/islandora_badges/blob/7.x/includes/admin.form.inc).

**Comment by mjordan** [comment]
Sounds like a good idea. Coincidentally, I just used that code in another local module. Small world!

**Comment by mjordan** [comment]
Resolved with 40777d568b165329a0146a31f3a6090bb5a06010.
