### ISSUE TITLE
Make step size adapt to large numbers

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_usage_stats_charts#20]
We probably need to change the Y axis step size to adapt to values. Currently, this is happening:

![charts](https://user-images.githubusercontent.com/403918/43403209-570eb9c6-93c9-11e8-9777-ffad1b680ab0.png)

We already do this for very small numbers, e.g. https://github.com/mjordan/islandora_usage_stats_charts/blob/7.x/js/usageStatsChart.js#L34.

**Comment by mjordan** [comment]
Worse example (maximum month is 3100 views):

![charts](https://user-images.githubusercontent.com/403918/43404716-00f44aca-93cd-11e8-91b5-fd9ca5c11a66.png)
This effect is likely what @bondjimbond is seeing in #18.

**Comment by bondjimbond** [comment]
@mjordan yes, if you look at https://arcabc.ca/islandora/object/kora%3Apublications# (source of screenshot in #18), you'll see that the highest number of views is 1295, while smallest is 67. Adaptive scale is needed... Is it possible to set a maximum number of steps? Or if not, we can set a maximum number of steps and do some simple math to get the stepSizeValue... How is it set currently?

**Comment by mjordan** [comment]
It's set in the Javascript that integrates Chart.js into the Drupal module, at https://github.com/mjordan/islandora_usage_stats_charts/blob/7.x/js/usageStatsChart.js#L34. We need some algorithm that will allow very high usage numbers to render as meaningfully as very small numbers. I like the idea of a maximum number of steps, e.g. 20.

**Comment by mjordan** [comment]
@bondjimbond can you test the issue-20 branch? I've set the step size to be 1/10 of the total, so we always have at most 10 steps. Here's the same usage chart as above running issue-20:

![cartoons_usage](https://user-images.githubusercontent.com/403918/43426764-b9d83eaa-940b-11e8-9b20-5d6d7f73eda6.png)

Be sure to test objects/collections with a lot of usage, plus objects with very little usage to ensure that the step size adjustments work on both the low and high end. Also test with high numbers of downloads if possible.

The logic is now:

* if the highest number of hits in a chart is greater than 50, adjust the step size to be 1/10 of that number
* if the highest number of hits in a chart is less than 10, adjust the step size to be 1 (otherwise by default it will show decimal points)
* if the highest number of hits in a chart is between 10 and 50, let it be the default (which varies depending on the number).

**Comment by bondjimbond** [comment]
Seems to work. Here are some screenshots: 
![screen shot 2018-08-01 at 3 32 33 pm](https://user-images.githubusercontent.com/6069170/43544324-8a6cfbb0-95a0-11e8-86e1-b076807bfc05.png)
![screen shot 2018-08-01 at 3 33 39 pm](https://user-images.githubusercontent.com/6069170/43544325-8a7f008a-95a0-11e8-8c24-2176df960456.png)
![screen shot 2018-08-01 at 3 34 55 pm](https://user-images.githubusercontent.com/6069170/43544326-8a8f0994-95a0-11e8-87cf-7442b3c633b3.png)

**Comment by bondjimbond** [comment]
Note, though, the weird increments. Typically you'd want to see round number increments on charts -- 1, 2, 5, 10, 50, etc. 373 is a weird number to appear on the Y-axis.

Would it be possible to do a little math and round the increments appropriately?

**Comment by mjordan** [comment]
Thanks for confirming that we've hit the problem with the scrunched Y axis. 

Currently the increments are the result of straight division by 10. If my math sense is correct, the maximum value will determine whether we should round up to the 10s, 100s, or 1000s (or with very large numbers, maybe the 10,000s?). Straight /10 may not look good but its simple..... can we live without the rounding?

**Comment by mjordan** [comment]
But am open to algorithms for rounding to match different maximum values.

**Comment by bondjimbond** [comment]
Apparently this is a pretty common problem, and somewhat complex. Easy for humans to do, harder for machines.

Possible helpful solution: http://austinclemens.com/blog/2016/01/09/an-algorithm-for-creating-a-graphs-axes/

**Comment by mjordan** [comment]
Good find but seems to verge on AI to me.... mind if I merge issue-20 and we open a new issue for this problem? That at least gets rid of the *munged* Y axis.

**Comment by bondjimbond** [comment]
Sounds good!

**Comment by mjordan** [comment]
Cool, thanks for testing, will merge in a bit. Feel free to open a new issue or let me know if you want me to.

**Comment by mjordan** [comment]
Closed with 6479c5a60f302eef58ee8b837d4fbe1048ef6c72.
