### ISSUE TITLE
Make Y axis step increments rounder

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_usage_stats_charts#24]
As noted toward the end of #20, the Chart.js "stepSize" increments in the Y axis adapt well to whatever maximum value is present in the chart, but they are defined by whatever 1/10 of the maximum number is, e.g.,

![example](https://user-images.githubusercontent.com/6069170/43544325-8a7f008a-95a0-11e8-8c24-2176df960456.png)

It would be nice to make the increments rounder. @mjordan points out that 

> the maximum value will determine whether we should round up to the 10s, 100s, or 1000s (or with very large numbers, maybe the 10,000s?). Straight /10 may not look good but its simple.....

and @bondjimbond points to http://austinclemens.com/blog/2016/01/09/an-algorithm-for-creating-a-graphs-axes/ as a potentially useful solution.

**Comment by mjordan** [comment]
@bondjimbond, here's a couple of screenshots showing rounded up to the nearest 100: first, for a chart with a max of 223 hits:

![rounded](https://user-images.githubusercontent.com/403918/43559137-945dbb16-95c1-11e8-80a1-0a3152cbae7b.png)

and for a chart with a max of 3104 hits:

![rounded](https://user-images.githubusercontent.com/403918/43559115-6fe9bc12-95c1-11e8-8f90-7cbd9977c4ea.png)

I assume that if the chart visualized tens or hundreds of thousands of hits, the steps would end in "00" but the thousands, tens of thousands, etc. might not be so rounded. But at least this makes everthing end in "00".

Mind testing the issue-24 branch?

**Comment by bondjimbond** [comment]
This is a big improvement. Seems to work well for small and large numbers of views. I'd say merge it.

**Comment by mjordan** [comment]
Great, thanks, done with 70d38fa23e38f1510345c841e86161766aae1b7e.
