### ISSUE TITLE
Curious behaviour: 0 views, 0 months

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_usage_stats_charts#25]
Just noticed on a collection I've never accessed before, that an object with zero views gets a chart showing "0 months".
![screen shot 2018-08-02 at 2 27 22 pm](https://user-images.githubusercontent.com/6069170/43606707-26505102-966a-11e8-823e-9f98751781b8.png)

I expect Islandora Usage Stats is not getting triggered the moment you navigate to the object, so when Charts reads the database it isn't counting the current view. That's probably fine (although strange and unexpected). It would be good to set a minimum 1 month in the chart, though.

**Comment by mjordan** [comment]
What would be the expected behavior if there were 0 months, to not show the chart?

**Comment by mjordan** [comment]
Or to display a message saying that there is no usage data for the current object?

**Comment by bondjimbond** [comment]
I'd probably prefer a message saying there is no usage data yet... of course, the next time they refresh, there will be. :)

**Comment by mjordan** [comment]
Depends on what the settings are in Usage Stats' "Omit IPs" and "Cooldown time" admin settings.

**Comment by bondjimbond** [comment]
True! But generally, "last 0 months" isn't very good. "No usage data for this object" would be better.

**Comment by mjordan** [comment]
This message could either be produced in the module's PHP code or in the Javascript bridge file. I'll take a look.

**Comment by mjordan** [comment]
OK, now if there is  no views data, the block contains "There is no usage data for this item." You will need to clear your cache to see this work since I had to touch the theme template for the block.

Closed with d1956eaac3f8cd1fdb0e551f4c43bfbd198d5cd1.
